DEBUG: False
OUTPUT_DIR: "output/slpr/ctw/baseline2/"
MODEL:
  META_ARCHITECTURE: "GeneralizedRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  # WEIGHT: "output/slpr/ctw/baseline/model_0020000.pth"
  STRICT: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.25, 0.5, 1.0, 2.0, 4.0)
    RPN_HEAD: "SingleConvRPNHead_1"
  RRPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.25, 0.5, 1.0, 2.0, 4.0)
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.85
    NMS: 0.3
  ROI_BOX_HEAD:
    DEFORMABLE_POOLING: False
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
    CLASS_WEIGHT: 1.0

  ## uncertainty border estimation
  UB_ON: True
  ROI_UB_HEAD:
    DEFORMABLE_POOLING: True
    FEATURE_EXTRACTOR: "UBRCNNFPNFeatureExtractor"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    PREDICTOR: "UBRCNNPredictor"
    RESOLUTION: 7
    BORDER_RATIO: 65
    UB_W_POINTS: 16
    UB_H_POINTS: 16
    SHARE_BOX_FEATURE_EXTRACTOR: False
    BO_WEIGHT: 0.1
    Loss_balance: 2.0
  LOGGING: True

PROCESS:
  PNMS: True
  NMS_THRESH: 0.25
DATASETS:
  TRAIN: ("CTW1500_train",)
  TEST: ("CTW1500_test",)
  Test_Visual: True
DATALOADER:
  SHUFFLE: False
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
SOLVER:
  GRADIENT_CLIP: 1.0
  BASE_LR: 0.005
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.0001
  STEPS: (20000, 25000)
  MAX_ITER: 30000
  IMS_PER_BATCH: 2
  CHECKPOINT_PERIOD: 5000
  EVAL_PERIOD: 1000
  EVAL_BEGIN: 20000

INPUT:
  MIN_SIZE_TRAIN: (400,600,720,1000,1200)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 720
  MAX_SIZE_TEST: 1280
  CROP_PROB_TRAIN: 1.0
  ROTATE_PROB_TRAIN: 0.0
  ROTATE_DEGREE: (0,30,60,90,210,150,180,210,240,270,300,330,360)

TEST:
  IMS_PER_BATCH: 2
  VIS_LOTM : False
  VIS_DIR : "debug/vis_ctw_LOTM4"