DEBUG: False
OUTPUT_DIR: "output/arrpnub/pretrain/synthtext/"
MODEL:
  META_ARCHITECTURE: "GeneralizedARRCNN"
  WEIGHT: "catalog://ImageNetPretrained/MSRA/R-50"
  STRICT: True
  BACKBONE:
    CONV_BODY: "R-50-FPN"
  FPN:
    USE_DEFORMABLE: False
  RESNETS:
    BACKBONE_OUT_CHANNELS: 256
  RPN:
    USE_FPN: True
    ANCHOR_STRIDE: (4, 8, 16, 32, 64)
    ASPECT_RATIOS: (0.25, 0.5, 1.0, 2.0, 4.0)
    RPN_HEAD: "SingleConvARPNHead"
  ARPN:
    BASE_SIZE: 640.
    SCALE_STACK: (0.25, 0.125, 0.0625, 0.03125, 0.015625)
    SIZE_STACK: (64, 128, 256, 512)
    NMS_TYPE: "remove"
    NMS_THRESH: 0.8
    SCORE_THRESH: 0.0
  ROI_HEADS:
    USE_FPN: True
    SCORE_THRESH: 0.52  # ic15
    NMS: 0.89
  ROI_BOX_HEAD:
    DEFORMABLE_POOLING: False
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    FEATURE_EXTRACTOR: "FPN2MLPFeatureExtractor"
    PREDICTOR: "FPNPredictor"
    NUM_CLASSES: 2
    CLASS_WEIGHT: 1.0

  ## uncertainty border estimation
  UB_ON: False
  ROI_UB_HEAD:
    GAUSSIAN: True
    CONF: False
    DEFORMABLE_POOLING: True
    FEATURE_EXTRACTOR: "UBRCNNFPNFeatureExtractor"
    POOLER_RESOLUTION: 7
    POOLER_SCALES: (0.25, 0.125, 0.0625, 0.03125)
    POOLER_SAMPLING_RATIO: 2
    PREDICTOR: "UBRCNNPredictor"
    RESOLUTION: 7
    BORDER_RATIO: 65
    UB_W_POINTS: 32
    UB_H_POINTS: 32
    SHARE_BOX_FEATURE_EXTRACTOR: False
    BO_WEIGHT: 0.1
    Loss_balance: 1.0
  LOGGING: True

PROCESS:
  PNMS: True
  NMS_THRESH: 0.25
DATASETS:
  TRAIN: ("synthtext_train",)
  TEST: ("ic15_test",)
  Test_Visual: True
DATALOADER:
  SHUFFLE: True
  NUM_WORKERS: 8
  SIZE_DIVISIBILITY: 32
SOLVER:
  GRADIENT_CLIP: 0.5
  BASE_LR: 0.001
  BIAS_LR_FACTOR: 2
  WEIGHT_DECAY: 0.0001
  STEPS: (700000, 760000)
  MAX_ITER: 800000
  IMS_PER_BATCH: 1
  CHECKPOINT_PERIOD: 40000
  EVAL_PERIOD: 1000
  EVAL_BEGIN: 800000

INPUT:
  MIN_SIZE_TRAIN: (400,600,720,800,1000,1200)
  MAX_SIZE_TRAIN: 2000
  MIN_SIZE_TEST: 1200
  MAX_SIZE_TEST: 2000
  CROP_PROB_TRAIN: 1.0
  ROTATE_PROB_TRAIN: 1.0
  ROTATE_DEGREE: (0,30,60,90,210,150,180,210,240,270,300,330,360)

TEST:
  IMS_PER_BATCH: 1